apiVersion: 1
datasources:
  - name: openquant
    type: frser-sqlite-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      path: /Users/gulshan/OpenQuant/data/journal/openquant.db
