//! Reference-test framework for feature indicators.
//!
//! Validates Rust implementations against independently computed reference
//! values (generated by `tools/generate_reftests.py` from pure math / numpy).
//!
//! # Design
//!
//! The framework is organized around two concepts:
//!
//! - **Fixtures**: JSON files with randomized OHLCV inputs and expected outputs,
//!   computed by a Python script that implements indicators from mathematical
//!   definitions — completely independent of this Rust code.
//!
//! - **Reference runners**: functions that feed fixture inputs through our Rust
//!   indicators and compare outputs at specific checkpoints against expected
//!   values within a configurable tolerance.
//!
//! # Extending
//!
//! To add reference tests for a new indicator:
//!
//! 1. Add the indicator computation to `tools/generate_reftests.py`
//! 2. Add expected values to the fixture JSON under `expected.<indicator_name>`
//! 3. Add a `#[test]` function below that extracts & compares values
//!
//! To add a new fixture (different market regime):
//!
//! 1. Add a `make_fixture(seed=..., ...)` call in the Python script
//! 2. Regenerate: `python tools/generate_reftests.py`
//! 3. All existing tests automatically pick up the new fixture

#[cfg(test)]
mod tests {
    use crate::features::*;
    use std::collections::HashMap;

    // ------------------------------------------------------------------
    // Framework: fixture loading and comparison helpers
    // ------------------------------------------------------------------

    /// Top-level fixture file structure.
    #[derive(serde::Deserialize)]
    struct FixtureFile {
        tolerance: f64,
        fixtures: Vec<Fixture>,
    }

    /// A single test fixture: inputs + expected outputs at checkpoints.
    #[derive(serde::Deserialize)]
    struct Fixture {
        label: String,
        inputs: Inputs,
        expected: HashMap<String, HashMap<String, f64>>,
        checkpoints: Vec<usize>,
    }

    #[derive(serde::Deserialize)]
    struct Inputs {
        closes: Vec<f64>,
        highs: Vec<f64>,
        lows: Vec<f64>,
        volumes: Vec<f64>,
    }

    /// Load all fixtures from the embedded JSON.
    fn load_fixtures() -> FixtureFile {
        let json = include_str!("reftest_fixtures.json");
        serde_json::from_str(json).expect("failed to parse reftest fixtures")
    }

    /// Assert two values are equal within tolerance, with a descriptive message.
    fn assert_close(actual: f64, expected: f64, tol: f64, ctx: &str) {
        let diff = (actual - expected).abs();
        assert!(
            diff < tol,
            "{ctx}: expected {expected:.12}, got {actual:.12} (diff={diff:.2e}, tol={tol:.0e})"
        );
    }

    /// Run a per-bar function over fixture inputs, collecting outputs at checkpoints.
    /// This is the core pattern: feed bars → snapshot at checkpoints → compare.
    fn run_checkpoints<S, F>(fixture: &Fixture, mut state: S, mut step: F) -> Vec<(usize, f64)>
    where
        F: FnMut(&mut S, f64, f64, f64, f64) -> f64,
    {
        let mut results = Vec::new();
        let checkpoint_set: std::collections::HashSet<usize> =
            fixture.checkpoints.iter().copied().collect();

        for i in 0..fixture.inputs.closes.len() {
            let val = step(
                &mut state,
                fixture.inputs.closes[i],
                fixture.inputs.highs[i],
                fixture.inputs.lows[i],
                fixture.inputs.volumes[i],
            );
            if checkpoint_set.contains(&i) {
                results.push((i, val));
            }
        }
        results
    }

    /// Compare checkpoint results against expected values for a named indicator.
    fn verify_indicator(
        fixture: &Fixture,
        indicator_name: &str,
        results: &[(usize, f64)],
        tol: f64,
    ) {
        let expected_map = fixture
            .expected
            .get(indicator_name)
            .unwrap_or_else(|| panic!("no expected values for '{indicator_name}'"));

        for &(bar, actual) in results {
            let key = bar.to_string();
            let expected = expected_map
                .get(&key)
                .unwrap_or_else(|| panic!("no expected value for {indicator_name} at bar {bar}"));
            assert_close(
                actual,
                *expected,
                tol,
                &format!("[{}] {indicator_name} @ bar {bar}", fixture.label),
            );
        }
    }

    /// Convenience: run an indicator over all fixtures and verify.
    fn verify_all_fixtures<S, F>(indicator_name: &str, make_state: impl Fn() -> S, step: F)
    where
        F: Fn(&mut S, f64, f64, f64, f64) -> f64 + Copy,
    {
        let file = load_fixtures();
        let tol = file.tolerance;
        for fixture in &file.fixtures {
            let results = run_checkpoints(fixture, make_state(), step);
            verify_indicator(fixture, indicator_name, &results, tol);
        }
    }

    // ------------------------------------------------------------------
    // Reference tests: one per indicator
    // ------------------------------------------------------------------

    #[test]
    fn reftest_ema_10() {
        verify_all_fixtures(
            "ema_10",
            || Ema::new(10),
            |ema, close, _, _, _| ema.push(close),
        );
    }

    #[test]
    fn reftest_ema_30() {
        verify_all_fixtures(
            "ema_30",
            || Ema::new(30),
            |ema, close, _, _, _| ema.push(close),
        );
    }

    #[test]
    fn reftest_wilder_14() {
        verify_all_fixtures(
            "wilder_14",
            || WilderEma::new(14),
            |w, close, _, _, _| w.push(close),
        );
    }

    #[test]
    fn reftest_sma_32() {
        verify_all_fixtures("sma_32", Sma::<32>::new, |sma, close, _, _, _| {
            sma.push(close)
        });
    }

    #[test]
    fn reftest_adx_14() {
        verify_all_fixtures(
            "adx_14",
            || Adx::new(14),
            |adx, close, high, low, _| {
                let (val, _, _) = adx.update(high, low, close);
                val
            },
        );
    }

    #[test]
    fn reftest_plus_di_14() {
        verify_all_fixtures(
            "plus_di_14",
            || Adx::new(14),
            |adx, close, high, low, _| {
                let (_, pdi, _) = adx.update(high, low, close);
                pdi
            },
        );
    }

    #[test]
    fn reftest_minus_di_14() {
        verify_all_fixtures(
            "minus_di_14",
            || Adx::new(14),
            |adx, close, high, low, _| {
                let (_, _, mdi) = adx.update(high, low, close);
                mdi
            },
        );
    }

    #[test]
    fn reftest_bollinger_upper() {
        // Bollinger uses SMA(32) + 2*std(close, 32). We need both SMA and RollingStats.
        struct BollingerState {
            sma: Sma<32>,
            stats: RollingStats<32>,
        }
        verify_all_fixtures(
            "bollinger_upper",
            || BollingerState {
                sma: Sma::new(),
                stats: RollingStats::new(),
            },
            |s, close, _, _, _| {
                let sma = s.sma.push(close);
                s.stats.push(close);
                sma + 2.0 * s.stats.std_dev()
            },
        );
    }

    #[test]
    fn reftest_bollinger_lower() {
        struct BollingerState {
            sma: Sma<32>,
            stats: RollingStats<32>,
        }
        verify_all_fixtures(
            "bollinger_lower",
            || BollingerState {
                sma: Sma::new(),
                stats: RollingStats::new(),
            },
            |s, close, _, _, _| {
                let sma = s.sma.push(close);
                s.stats.push(close);
                sma - 2.0 * s.stats.std_dev()
            },
        );
    }

    #[test]
    fn reftest_bollinger_pct_b() {
        struct BollingerState {
            sma: Sma<32>,
            stats: RollingStats<32>,
        }
        verify_all_fixtures(
            "bollinger_pct_b",
            || BollingerState {
                sma: Sma::new(),
                stats: RollingStats::new(),
            },
            |s, close, _, _, _| {
                let sma = s.sma.push(close);
                s.stats.push(close);
                let std = s.stats.std_dev();
                let upper = sma + 2.0 * std;
                let lower = sma - 2.0 * std;
                let width = upper - lower;
                if width > 1e-10 {
                    (close - lower) / width
                } else {
                    0.5
                }
            },
        );
    }

    #[test]
    fn reftest_bollinger_bandwidth() {
        struct BollingerState {
            sma: Sma<32>,
            stats: RollingStats<32>,
        }
        verify_all_fixtures(
            "bollinger_bandwidth",
            || BollingerState {
                sma: Sma::new(),
                stats: RollingStats::new(),
            },
            |s, close, _, _, _| {
                let sma = s.sma.push(close);
                s.stats.push(close);
                let std = s.stats.std_dev();
                let upper = sma + 2.0 * std;
                let lower = sma - 2.0 * std;
                let width = upper - lower;
                if sma > 1e-10 { width / sma } else { 0.0 }
            },
        );
    }

    // ------------------------------------------------------------------
    // V3 reference tests: VWAP, Donchian, Bandwidth Percentile
    // ------------------------------------------------------------------

    #[test]
    fn reftest_vwap() {
        let file = load_fixtures();
        let tol = file.tolerance;
        for fixture in &file.fixtures {
            let mut state = vwap::VwapState::default();
            let mut results = Vec::new();
            for i in 0..fixture.inputs.closes.len() {
                // timestamp=0 means no daily reset (single session)
                let vals = state.update(
                    fixture.inputs.highs[i],
                    fixture.inputs.lows[i],
                    fixture.inputs.closes[i],
                    fixture.inputs.volumes[i],
                    0,
                );
                if fixture.checkpoints.contains(&i) {
                    results.push((i, vals.vwap));
                }
            }
            verify_indicator(fixture, "vwap", &results, tol);
        }
    }

    #[test]
    fn reftest_vwap_deviation() {
        let file = load_fixtures();
        let tol = file.tolerance;
        for fixture in &file.fixtures {
            let mut state = vwap::VwapState::default();
            let mut results = Vec::new();
            for i in 0..fixture.inputs.closes.len() {
                let vals = state.update(
                    fixture.inputs.highs[i],
                    fixture.inputs.lows[i],
                    fixture.inputs.closes[i],
                    fixture.inputs.volumes[i],
                    0,
                );
                if fixture.checkpoints.contains(&i) {
                    results.push((i, vals.deviation));
                }
            }
            verify_indicator(fixture, "vwap_deviation", &results, tol);
        }
    }

    #[test]
    fn reftest_vwap_z_score() {
        let file = load_fixtures();
        let tol = file.tolerance;
        for fixture in &file.fixtures {
            let mut state = vwap::VwapState::default();
            let mut results = Vec::new();
            for i in 0..fixture.inputs.closes.len() {
                let vals = state.update(
                    fixture.inputs.highs[i],
                    fixture.inputs.lows[i],
                    fixture.inputs.closes[i],
                    fixture.inputs.volumes[i],
                    0,
                );
                if fixture.checkpoints.contains(&i) {
                    results.push((i, vals.z_score));
                }
            }
            verify_indicator(fixture, "vwap_z_score", &results, tol);
        }
    }

    #[test]
    fn reftest_donchian_upper() {
        verify_all_fixtures(
            "donchian_upper",
            donchian::Donchian::<32>::new,
            |d, _close, high, low, _vol| {
                let vals = d.update(high, low);
                vals.upper
            },
        );
    }

    #[test]
    fn reftest_donchian_lower() {
        verify_all_fixtures(
            "donchian_lower",
            donchian::Donchian::<32>::new,
            |d, _close, high, low, _vol| {
                let vals = d.update(high, low);
                vals.lower
            },
        );
    }

    #[test]
    fn reftest_donchian_mid() {
        verify_all_fixtures(
            "donchian_mid",
            donchian::Donchian::<32>::new,
            |d, _close, high, low, _vol| {
                let vals = d.update(high, low);
                vals.mid
            },
        );
    }

    #[test]
    fn reftest_bandwidth_percentile() {
        // Bandwidth percentile depends on Bollinger bandwidth, so we need
        // to compute Bollinger first, then feed bandwidth to the percentile tracker.
        struct State {
            sma: Sma<32>,
            stats: RollingStats<32>,
            bp: donchian::BandwidthPercentile<64>,
        }
        verify_all_fixtures(
            "bandwidth_percentile",
            || State {
                sma: Sma::new(),
                stats: RollingStats::new(),
                bp: donchian::BandwidthPercentile::new(),
            },
            |s, close, _, _, _| {
                let sma = s.sma.push(close);
                s.stats.push(close);
                let std = s.stats.std_dev();
                let upper = sma + 2.0 * std;
                let lower = sma - 2.0 * std;
                let width = upper - lower;
                let bandwidth = if sma > 1e-10 { width / sma } else { 0.0 };
                s.bp.push(bandwidth)
            },
        );
    }

    // ------------------------------------------------------------------
    // Full pipeline reference test: FeatureState end-to-end
    // ------------------------------------------------------------------

    #[test]
    fn reftest_feature_state_pipeline() {
        // Verify that FeatureState produces the same values as individual
        // indicators — catches wiring bugs in the orchestrator.
        let file = load_fixtures();
        let tol = file.tolerance;

        for fixture in &file.fixtures {
            let mut state = FeatureState::new();

            for i in 0..fixture.inputs.closes.len() {
                let f = state.update(
                    fixture.inputs.closes[i],
                    fixture.inputs.highs[i],
                    fixture.inputs.lows[i],
                    fixture.inputs.volumes[i],
                    0, // no timestamp for reftests
                );

                if fixture.checkpoints.contains(&i) {
                    let key = i.to_string();
                    let label = &fixture.label;

                    // EMA
                    assert_close(
                        f.ema_fast,
                        fixture.expected["ema_10"][&key],
                        tol,
                        &format!("[{label}] pipeline ema_fast @ bar {i}"),
                    );
                    assert_close(
                        f.ema_slow,
                        fixture.expected["ema_30"][&key],
                        tol,
                        &format!("[{label}] pipeline ema_slow @ bar {i}"),
                    );

                    // ADX
                    assert_close(
                        f.adx,
                        fixture.expected["adx_14"][&key],
                        tol,
                        &format!("[{label}] pipeline adx @ bar {i}"),
                    );
                    assert_close(
                        f.plus_di,
                        fixture.expected["plus_di_14"][&key],
                        tol,
                        &format!("[{label}] pipeline plus_di @ bar {i}"),
                    );
                    assert_close(
                        f.minus_di,
                        fixture.expected["minus_di_14"][&key],
                        tol,
                        &format!("[{label}] pipeline minus_di @ bar {i}"),
                    );

                    // Bollinger
                    assert_close(
                        f.bollinger_upper,
                        fixture.expected["bollinger_upper"][&key],
                        tol,
                        &format!("[{label}] pipeline bollinger_upper @ bar {i}"),
                    );
                    assert_close(
                        f.bollinger_lower,
                        fixture.expected["bollinger_lower"][&key],
                        tol,
                        &format!("[{label}] pipeline bollinger_lower @ bar {i}"),
                    );
                    assert_close(
                        f.bollinger_pct_b,
                        fixture.expected["bollinger_pct_b"][&key],
                        tol,
                        &format!("[{label}] pipeline bollinger_pct_b @ bar {i}"),
                    );
                    assert_close(
                        f.bollinger_bandwidth,
                        fixture.expected["bollinger_bandwidth"][&key],
                        tol,
                        &format!("[{label}] pipeline bollinger_bandwidth @ bar {i}"),
                    );

                    // VWAP
                    assert_close(
                        f.vwap,
                        fixture.expected["vwap"][&key],
                        tol,
                        &format!("[{label}] pipeline vwap @ bar {i}"),
                    );
                    assert_close(
                        f.vwap_deviation,
                        fixture.expected["vwap_deviation"][&key],
                        tol,
                        &format!("[{label}] pipeline vwap_deviation @ bar {i}"),
                    );
                    assert_close(
                        f.vwap_z_score,
                        fixture.expected["vwap_z_score"][&key],
                        tol,
                        &format!("[{label}] pipeline vwap_z_score @ bar {i}"),
                    );

                    // Donchian
                    assert_close(
                        f.donchian_upper,
                        fixture.expected["donchian_upper"][&key],
                        tol,
                        &format!("[{label}] pipeline donchian_upper @ bar {i}"),
                    );
                    assert_close(
                        f.donchian_lower,
                        fixture.expected["donchian_lower"][&key],
                        tol,
                        &format!("[{label}] pipeline donchian_lower @ bar {i}"),
                    );
                    assert_close(
                        f.donchian_mid,
                        fixture.expected["donchian_mid"][&key],
                        tol,
                        &format!("[{label}] pipeline donchian_mid @ bar {i}"),
                    );

                    // Bandwidth percentile
                    assert_close(
                        f.bandwidth_percentile,
                        fixture.expected["bandwidth_percentile"][&key],
                        tol,
                        &format!("[{label}] pipeline bandwidth_percentile @ bar {i}"),
                    );
                }
            }
        }
    }
}
