"""
One-time environment preparation for OpenQuant autoresearch.
Verifies Rust toolchain, builds the runner, checks Alpaca API keys.

Usage: python prepare.py

This is the READ-ONLY harness. The LLM must NOT modify this file.
"""

import os
import sys
import subprocess
import json

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENGINE = os.path.join(ROOT, "engine")
RUNNER = os.path.join(ENGINE, "target", "release", "openquant-runner")
ENV_FILE = os.path.join(ROOT, ".env")
SP500_FILE = os.path.join(ROOT, "data", "sp500_sectors.json")
PAIRS_CONFIG = os.path.join(ROOT, "config", "pairs.toml")
ACTIVE_PAIRS = os.path.join(ROOT, "trading", "active_pairs.json")
CANDIDATES = os.path.join(ROOT, "trading", "pair_candidates.json")


def check_rust():
    """Verify Rust toolchain is available."""
    print("Checking Rust toolchain...")
    try:
        result = subprocess.run(
            ["cargo", "--version"], capture_output=True, text=True, check=True
        )
        print(f"  {result.stdout.strip()}")
    except (FileNotFoundError, subprocess.CalledProcessError):
        print("ERROR: cargo not found. Install Rust: https://rustup.rs/")
        sys.exit(1)


def build_runner():
    """Build the openquant-runner binary in release mode."""
    print("Building openquant-runner (release)...")
    result = subprocess.run(
        ["cargo", "build", "--release", "-p", "openquant-runner"],
        cwd=ENGINE,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print("BUILD FAILED:")
        print(result.stderr[-2000:] if len(result.stderr) > 2000 else result.stderr)
        sys.exit(1)
    print(f"  Binary: {RUNNER}")
    assert os.path.exists(RUNNER), f"Runner not found at {RUNNER}"


def check_alpaca_keys():
    """Verify Alpaca API keys exist in .env."""
    print("Checking Alpaca API keys...")
    if not os.path.exists(ENV_FILE):
        print(f"ERROR: {ENV_FILE} not found. Create it with ALPACA_API_KEY and ALPACA_SECRET_KEY.")
        sys.exit(1)
    with open(ENV_FILE) as f:
        content = f.read()
    has_key = "ALPACA_API_KEY" in content
    has_secret = "ALPACA_SECRET_KEY" in content
    if not has_key or not has_secret:
        print("ERROR: .env must contain ALPACA_API_KEY and ALPACA_SECRET_KEY")
        sys.exit(1)
    print("  API keys found.")


def check_data_files():
    """Verify required data files exist."""
    print("Checking data files...")
    files = {
        "S&P 500 sectors": SP500_FILE,
        "Pairs config": PAIRS_CONFIG,
        "Pair candidates": CANDIDATES,
    }
    for name, path in files.items():
        if os.path.exists(path):
            size = os.path.getsize(path)
            print(f"  {name}: {path} ({size:,} bytes)")
        else:
            print(f"  WARNING: {name} not found at {path}")

    # Active pairs (optional — pair-picker regenerates during replay)
    if os.path.exists(ACTIVE_PAIRS):
        with open(ACTIVE_PAIRS) as f:
            data = json.load(f)
        n = len(data.get("pairs", []))
        print(f"  Active pairs: {n} pairs loaded")
    else:
        print("  Active pairs: will be generated by pair-picker during replay")


def check_runner_works():
    """Quick smoke test — run the runner with --help."""
    print("Smoke testing runner...")
    result = subprocess.run(
        [RUNNER, "--help"], capture_output=True, text=True
    )
    if result.returncode == 0:
        print("  Runner responds to --help. Ready.")
    else:
        print(f"ERROR: Runner failed. stderr: {result.stderr[:500]}")
        sys.exit(1)


if __name__ == "__main__":
    print("=" * 60)
    print("OpenQuant Autoresearch — Environment Preparation")
    print("=" * 60)
    print()

    check_rust()
    print()
    build_runner()
    print()
    check_alpaca_keys()
    print()
    check_data_files()
    print()
    check_runner_works()

    print()
    print("=" * 60)
    print("Setup complete. Ready to run experiments.")
    print()
    print("Next: python train.py > run.log 2>&1")
    print("Then: grep '^avg_bps:' run.log")
    print("=" * 60)
